-- Execute este arquivo no SQL Editor do Supabase.
-- O acesso anonimo permite o prototipo funcionar sem cadastro;
-- para producao, adicione autenticacao, moderacao e rate limit.

create extension if not exists pgcrypto;

create table if not exists public.missing_person_posts (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 120),
  age text,
  city text not null check (char_length(city) between 2 and 120),
  last_contact text not null check (char_length(last_contact) between 2 and 200),
  characteristics text not null check (char_length(characteristics) between 20 and 2000),
  contact text not null check (char_length(contact) between 5 and 80),
  photo_url text not null,
  gallery text[] not null default '{}',
  status text not null default 'desaparecida' check (status in ('desaparecida', 'encontrada')),
  created_at timestamptz not null default now()
);

create table if not exists public.missing_person_messages (
  id bigint generated by default as identity primary key,
  sender_name text not null default 'Anonimo' check (char_length(sender_name) between 1 and 40),
  message text not null check (char_length(message) between 1 and 500),
  created_at timestamptz not null default now()
);

-- Migração segura para projetos que já tinham a tabela criada.
alter table public.missing_person_posts add column if not exists gallery text[] not null default '{}';
alter table public.missing_person_posts add column if not exists status text not null default 'desaparecida';
alter table public.missing_person_posts drop constraint if exists missing_person_posts_status_check;
alter table public.missing_person_posts add constraint missing_person_posts_status_check check (status in ('desaparecida', 'encontrada'));

alter table public.missing_person_posts enable row level security;
alter table public.missing_person_messages enable row level security;

grant select, insert, update, delete on public.missing_person_posts to anon;
grant select, insert on public.missing_person_messages to anon;

drop policy if exists "public can read missing posts" on public.missing_person_posts;
create policy "public can read missing posts" on public.missing_person_posts for select to anon using (true);

drop policy if exists "public can publish missing posts" on public.missing_person_posts;
create policy "public can publish missing posts" on public.missing_person_posts for insert to anon with check (true);

drop policy if exists "public can update missing posts" on public.missing_person_posts;
create policy "public can update missing posts" on public.missing_person_posts for update to anon using (true) with check (true);

drop policy if exists "public can delete missing posts" on public.missing_person_posts;
create policy "public can delete missing posts" on public.missing_person_posts for delete to anon using (true);

drop policy if exists "public can read chat messages" on public.missing_person_messages;
create policy "public can read chat messages" on public.missing_person_messages for select to anon using (true);

drop policy if exists "public can send chat messages" on public.missing_person_messages;
create policy "public can send chat messages" on public.missing_person_messages for insert to anon with check (true);

insert into storage.buckets (id, name, public)
values ('missing-photos', 'missing-photos', true)
on conflict (id) do update set public = true;

drop policy if exists "public can read missing photos" on storage.objects;
create policy "public can read missing photos" on storage.objects for select to anon using (bucket_id = 'missing-photos');

drop policy if exists "public can upload missing photos" on storage.objects;
create policy "public can upload missing photos" on storage.objects for insert to anon with check (bucket_id = 'missing-photos');

alter table public.missing_person_messages replica identity full;
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'missing_person_messages'
  ) then
    alter publication supabase_realtime add table public.missing_person_messages;
  end if;
end
$$;
